### ISSUE TITLE
Edit image option

### ISSUE THREAD

**Issue by avaudagna** [yanzhenjie/Album#31]
What do you think of adding this kind of functionality to the library? 

![00_aviary_-_orientation](https://cloud.githubusercontent.com/assets/4071182/25288673/c42f135c-269c-11e7-945d-14eeb98a4319.png)

Would be specially useful at the time of choosing a profile picture with Album.

**Comment by yanzhenjie** [comment]
Your proposal is great, this plan is being developed, is expected to be available after 24 hours, waiting for good news.

**Comment by yanzhenjie** [comment]
Very sorry, I encountered a little trouble in the development time, time may be longer, but I will be as soon as possible, I will reply to you after the development is complete.

**Comment by yanzhenjie** [comment]
Very sorry, some time ago because of the work is busy, so the "Image Crop" program delayed for a long time. But it is now happy, because the "Image Crop" has been perfectly supported, it is a separate library, do not limit the need to be used with the Album, but they are used together is the best.  
It.s name is **Durban**: [https://github.com/yanzhenjie/Durban](https://github.com/yanzhenjie/Durban)

**Comment by yanzhenjie** [comment]
Completed, no response, closed.
